### ISSUE TITLE
Check level generation is valid

### ISSUE THREAD

**Issue by junhaoyap** [MrFool/Cattac#12]
Do not trap cat amongst others

**Comment by stevenkhong** [comment]
Let me try defining the algo before I start
- All cat-spawning nodes (seems to be fixed on 4 corners) are linked with edges.
- If non-cat entity is trapped in unreachable node, delete entity (reduce need to regenerate)
- Not to forget wormhole linkages in calculating reachability

If there's any checks I left out please comment below. Thanks
@MrFool @justwudi

**Comment by junhaoyap** [comment]
I do later, you focus on item gen!

**Comment by stevenkhong** [comment]
Actually I can do this if you're okay with it. You have a whole of issues man. @MrFool
