### ISSUE TITLE
Connection Manager

### ISSUE THREAD

**Issue by justwudi** [MrFool/Cattac#31]
Using a facade pattern, wraps all the specific implementations of `firebase`/`parse`/`DIY servers` so that everything can be called with one `ConnectionManager`.

Enforce all servers to implement a `Server` protocol that the `ConnectionManager` can call.

Basic functionality are those that `firebase` have:
- reading given a path
- writing values/dictionary to a path
- watching for changes

Possible to create another specific `GameConnectionManager` that uses the methods of the `ConnectionManager` for methods such as `createTurn`/`turnEnded`

**Comment by junhaoyap** [comment]
#78

**Comment by junhaoyap** [comment]
Closing, should be ok liao, just need to extract into a library for when meeting prof
