### ISSUE TITLE
Ability to poop

### ISSUE THREAD

**Issue by junhaoyap** [MrFool/Cattac#57]

**Comment by stevenkhong** [comment]
Lets decide:
**Poop before-move**
- [x] Steven
- [x] Wu Di
- [x] @MrFool 

**Poop after-move**

**Yet to vote**

Yayy. decided "poop then run away"

**Comment by junhaoyap** [comment]
We do poop before moving then, but take note of #71 and that in the case whether we should allow action before movement cause right now if we try to perform movement after movement + action, the action is cancelled

**Comment by stevenkhong** [comment]
Can't find the commit, but this is fixed in pull request for feature/poop-action #70.
Discussion on action & movement precedence issue will be continued on issue #71.
